finetune_from: models/single_dataset/real/res01/TAGConv/no-vn/siamese/p-1/mse_loss/w-64-hw-128-dropout/debug/new/
train_data: generated/res01_phase1.npz
epochs: 1000
device: cuda
batch_size: 256
dataset_name: generated/res01_phase1.npz
config: configs/w-64-hw-128-dropout.yml
siamese: 1
vn: 0
max: 1
loss: mse_loss
aggr: 'sum+diff'
layer_type: 'TAGConv'
p: 1
include_edge_attr: 1
finetune: 1
uncertainty_model: 0
lr: 0.001
