train_data: generated/res20_phase1.npz
test_data: generated/res20_phase2.npz
epochs: 500
device: cuda
batch_size: 256
dataset_name: real/res20
config: configs/w-64-hw-128-dropout.yml
siamese: 1
vn: 0
max: 1
loss: mse_loss
aggr: 'sum+diff'
layer_type: 'GATConv'
p: 1
include_edge_attr: 1
finetune: 0
lr: 0.0001
finetune_from: 'none'